### ISSUE TITLE
When I drag and drop a table to editor, I see an error

### ISSUE THREAD

**Issue by allenhwkim** [VojtechLanka/grapesjs-blocks-table#7] opened 2023-12-11 16:49 UTC
When I drag and drop a table to editor, I see an error
![image](https://github.com/VojtechLanka/grapesjs-blocks-table/assets/1437734/d798f72f-54ca-4bee-b54f-8b9c3e63ca75)

![image](https://github.com/VojtechLanka/grapesjs-blocks-table/assets/1437734/839a8b94-1f0e-497d-b513-de5611b94c9a)

![image](https://github.com/VojtechLanka/grapesjs-blocks-table/assets/1437734/b7faa784-b9eb-475e-816d-d3501f800a5b)

https://codesandbox.io/p/sandbox/table-forked-94xdwf?file=%2Fsrc%2Findex.js%3A14%2C1

However, it seems working with the old version, 0.0.118
![image](https://github.com/VojtechLanka/grapesjs-blocks-table/assets/1437734/cc4dce67-f201-44fc-861c-63457744c12d)

**Comment by VojtechLanka** [comment] 2023-12-11 17:07
Hi, thanks for the report.
It has been a while since I worked on this but if I remember correctly the plugin works under the assumption that `editor` is globaly defined variable that holds the result of `grapesjs.init()`.

For some reason the codesandbox is not loading for me, and I have no idea why it would work with the older version but not with the new one.

**Comment by VojtechLanka** [comment] 2024-01-30 16:00
Hello, sorry for the wait my full time job keeps me occupied.
Looking at it in detail the problem is that several helper functions expect the `editor` to be globally available. In the example you provided the problem can be fixed by doing `window.editor = editor;`. This approach was fine when I original developed this plugin but I am no longer so sure of it.

I have created new version [v1.2.0](https://github.com/VojtechLanka/grapesjs-blocks-table/releases/tag/v1.2.0) that should address this issue.

Please let me know if it works as expected.

**Comment by VojtechLanka** [comment] 2024-04-26 12:02
Closing due to no activity.

**Closed as completed by VojtechLanka** 2024-04-26 12:02 UTC
Labels: bug
